### ISSUE TITLE
Why do you need tTrR in your codepage?

### ISSUE THREAD

**Issue by GolfingSuccess** [lvivtotoro/lolo#2]
Just that one.

**Comment by lvivtotoro** [comment]
In future releases the program may behave differently depending on whether you have tR, Tr, TR or tr in the beginning of your program.

**Comment by erikkonstas** [comment]
@lvivtotoro Oh, I would have made a smaller codepage instead though, and expanded it later... Also why do you have a separate codepage?

**Comment by lvivtotoro** [comment]
Because it's fun. It's like your own encoding.

**Comment by erikkonstas** [comment]
@lvivtotoro Does the interpreter read in UTF-8 or the characters NUL - TAB?
